language: php
php:
  - '7.1'
install:
  - composer install
script:
  - ls -la
  - zip -v
  - zip -r ZS-plugin-rips.zip deployment.json EULA LICENSE logo.png README.md ui/ vendor/
  
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: ZS-plugin-rips.zip
  skip_cleanup: true
  on:
    tags: true
